### ISSUE TITLE
Add Kwil to Data Storage Companies

### ISSUE THREAD

**Issue by KwilLuke** [OpenDataforWeb3/Landscape#5]
**Data sharing**
Decentralized databases for storing off-chain data.

**Kwil:**
- Website: https://www.kwil.com/
- Docs: https://docs.kwil.com/
- Summary: Kwil is a permissionless SQL database that enables decentralized, structured data storage for off-chain data.

**Comment by epowell101** [comment]
Hi @KwilLuke - I'm just getting around to closing this one since we added Kwil some time ago.

We have a hackathon coming up in January btw that might be an opportunity to collaborate.  Drop into the discord to find the draft plan and/or join an upcoming Tuesday am community call to discuss synchronously please
